number: '0123456789'
# symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
# lang_char: |
#   あ ぃ い う ぇ え お か が き ぎ く ぐ け げ こ ご さ ざ し じ す ず せ ぜ そ ぞ た だ ち ぢ っ つ づ て で と ど な に
#   ぬ ね の は ば ぱ ひ び ぴ ふ ぶ ぷ へ べ ぺ ほ ぼ ぽ ま み む め も ゃ や ゅ ゆ ょ よ ら り る れ ろ わ を ん ァ ア ィ 
#   イ ゥ ウ ェ エ ォ オ カ ガ キ ギ ク グ ケ ゲ コ ゴ サ ザ シ ジ ス ズ セ ゼ ソ ゾ タ ダ チ ヂ ッ ツ ヅ テ デ ト ド ナ ニ 
#   ヌ ネ ノ ハ バ パ ヒ ビ ピ フ ブ プ ヘ ベ ペ ホ ボ ポ マ ミ ム メ モ ャ ヤ ュ ユ ョ ヨ ラ リ ル レ ロ ワ ヱ ヲ ン ヴ ヶ 
#   ・ 日	事 人	一 見	本 子	出 年	大 言	学 分	中 記	会 新	月 時 行 気	報 思	上 語	自 者	生 文	明 情	国 朝	用 書	私 手	間 小	
#   合 方	社 検	目 前	入 索	関 作	特 何	女 今	体 動	集 発	最 内	投 下	知 地	場 別	話 部	化 告	法 広	来 田	理 物	開 全	説 聞	
#   表 連	無 対	的 高	教 感	心 以	成 名	業 長	家 稿	定 実	山 近	現 後	金 覧	男 画	性 度	数 立	彼 問	二 意	能 個	僕 通	面 回	
#   代 木 利 経 使 車 編 同 平 音 読 少 食 道 世 結 力 楽 真 品 考 公 野 込 所 不 当 取 在 電 愛 外 載 向 美 返 仕 版 際 変 
#   示 親 治 政 島 権 解 他 先 掲 川 三 口 機 風 東 市 付 持 式 加 界 要 信 多 更 活 選 題 屋 論 郎 済 有 身 線 味 著 顔 売 
#   空 続 第 様 海 始 校 英 勝 母 次 点 正 科 京 術 転 録 初 葉 相 約	終 育	住 白	等 声	俺 字	決 登	北 案	天 産	切 都	格 主	
#   県 着	健 調	芸 違	研 古	参 番	館 受	歩 値	歴 笑	引 形	村 然	果 和	究 重	西 議	奈 直	確 強	注 組	良 辞	好 試	可 水	必 送	
#   万 止 帰 典 再 門 写 神 供 紹 運 設 宮 色 推 期 員 映 球 技 落 放 紀 岡 藤 計 予 達 図 支 追 張 去 応 康 夜 民 光 父 工 
#   頭 配 進 験 号 段 囲 宇 由 企 米 細 商 太 置 待 早 右 念 棋 友 断 佐 半 害 帯 像 票 提 覚 件 得 展 悪 室 福 起 乗 制 交 
#   病 各	質 千	構 限	優 残	院 週	詩 星	横 基	規 完	伝 募	総 宙	氏 職	詳 旅	買 位	史 青	将 条	博 履	単 順	存 突	崎 毎	夫 歌	
#   五 飛	深 誰	座 談	務 婚	演 頼	価 戸	消 評	例 義	常 板	視 左	振 医	統 坂	団 台	静 申	素 香	域 四	観 購	陽 首	局 石	戻 認	
#   識 興	呼 類	速 状	製 係	馬 共	護 並	降 君	路 雨	省 求	沢 百	側 土	離 反	曜 種	紙 象	助 頃	飲 携	望 散	財 判	難 秋	曲 姿	
#   舞 師	疑 境	探 満	純 谷	了 清	程 花	答 碁	火 南	背 駅	器 環	補 夢	材 施	差 標	園 両	命 障	微 禁	黒 建	営 森	根 協	冷 走	
#   折 量	端 居	任 若	造 負	項 松	橋 区	型 依	街 故	管 抜	司 茨	士 態	押 印	幸 改	独 系	整 息	衛 宅	習 移	犬 株	阪 訳	殺 弘	
#   隆 犯	兄 急	寄 収	休 堂	割 志	兵 忘	赤 打	影 州	階 樹	修 六	客 察	夏 雑	之 歳	処 緒	絡 罪	照 浮	軽 窓	含 弱	換 準	異 賞	
#   嫌 希	苦 酒	査 刊	欲 池	般 宗	沖 失	未 尾	渡 役	景 列	草 破	針 周	接 城	林 薦 八 販	寝 熱	我 便	奇 証	導 角	具 願	至 遠	
#   片 老	末 責	瞬 途	挙 族	専 絵	響 波	吉 絶	茶 暮	盗 授	貴 悩	遊 幻 撃 効 普 杯 王 策 簡 焼 宝 遅 療 鉄 乳 与 算 玉 浜 逃 
#   府 創 働 津 増 復 余 児 援 競 抱 装 雄 恋 央 越 久 賀 九 暗 謝 江 里 眠 非 鮮 似 冬 激 極 替 春 薬 痛 留 警 血 曰 巨 払 
#   比 席 備 防 章 脳 費 刷 誤 災 複 触 辺 幅 薄 猫 税 低 縄 布 李 争 精 為 誌 狙 髪 節 勢 許 昨 庫 銀 涼 傷 萌 徳 鹿 億 御 
#   除 筋 胸 倒 裁 洋 及 講 源 茄 領 倉 鳥 札 群 採 妻 裏 刻 派 険 夕 怪 梢 閉 訴 娘 恵 被 適 互 岩 執 震 積 占 富 繁 亡 眼 
#   皆 雪 壊 武 捕 模 帳 守 催 掛 仲 枚 困 避 耳 労 透 隣 七 測 陸 魅 勉 煙 砂 慣 奥 肉 述 概 勤 恐 射 吹 宿 況 服 課 午 韓 
#   短 浩 鳴 黙 殿 壁 聖 舎 昔 借 従 拠 継 籍 孝 密 率 築 束 庭 裕 温 担 祭 驚 則 鈴 混 珠 昼 超 略 遺 己 漫 矢 腕 婦 牧 巻 
#   届 飯 劇 幕 刑 底 華 惑 衆 竹 哲 伸 脱 泣 趣 腹 誘 筆 昇 敗 候 減 悟 怖 聴 妙 拍 致 融 揺 伊 乱 晴 軍 額 就 憶 脆 迷 船 
#   諸 肩	騒 疲	踏 悲	級 仙	尚 港	賃 亜	択 吸	扱 床	律 永	也 丸	包 隠	逮 納	輝 爆	党 退	否 称 熊 症	析 滅	羽 丈	駆 植	診 燃	
#   骨 奴	河 鶴	刺 牛	雲 仁	令 描 魚 徒	輪 喜	功 握	闇 盛	迎 俊 魔 匂	献 豊	庁 龍	卒 削	弾 姉	闘 層	固 繰	礼 梨	官 委	寒 腰	
#   駄 挫	酔 監	怒 毛	紅 操	涙 因	桜 快	給 袋	迫 眺	坊 弁	革 虫	衣 染	荒 幾	童 幼	敵 充	儀 詰	曇 跡	皮 釈	捨 訪	締 逆	荷 液	
#   練 織	勇 臨	慎 蔵	攻 栃	承 停	農 礎	潟 属	埼 那	滋 討	抗 毅	弟 季	甲 叫	麺 績	棚 才	沈 既	券 亀	免 湯	鼻 濡	泉 厚	厳 救	
#   欠 圧	覆 絞	霊 油	看 幹	房 哉	炎 輸	岐 勧	範 誕	秘 危	孤 悠	漢 易	麻 吐	灯 幌	訟 翼	埋 鏡	頬 瀬	句 邪	洞 靴	俗 蟻	善 丁	
#   頑 慢	塾 洗	寂 督	秀 請	契 叩	患 汗	泊 侵	豪 枝	衝 倍	潰 圭	唇 署	到 陰	貨 傾	徴 益	箱 黄	寺 栄	頂 託	巡 欧	仏 仮	狭 均
#   網 副	肌 翻	嘘 阜	剣 昭	臭 挑	飾 踊	塚 棄	茂 崩	干 悔	喫 滝	遣 奏	齢 盤	尋 詞	懸 妊	喋 媛	宣 閣	損 騎	濃 僚	雇 隊	暇 辛	
#   覇 拡 浴 冗 鑑 郵 養 柱 距 妄 桐 銃 甘 銭 阿 嬉 橘 伯 柄 狂 尽 泰 併 輔 矩 恥 乾 柳 緊 随 較 暦 汚 核 臓 歯 脚 郡 誠 菜 
#   奪 渋 敦 冊 岸 躍 旧 晩 瞳 鍵 航 雰 扉 郷 延 襲 屈 祥 勘 縁 控 漏 智 克 凍 憲 圏 暴 搭 彩 緑 竜 焦 柔 撮 坦 陶 祈 仰 机 
#   謎 玄 麗 藩 暖 獣 欣 敷 又 隅 露 暑 尻 捜 呆 潜 豆 双 咲 覗 祖 畿 縮 葬 貸 舗 顧 祝 霧 漁 拓 摩 債 努 綾 雷 廊 審 賢 贈 
#   翔 噂 掴 舌 翅 塗 但 却 慌 浅 祉 卓 摘 掌 浦 抑 缶 懐 哀 廃 湾 盲 序 湖 偶 苛 償 旬 穴 羅 隙 篇 招 寛 忙 漂 抵 嶋 添 膝 
#   促 貯 批 挨 拶 脇 即 拐 皇 閲 嵐 傍 寿 彦 翌 邦 徹 縛 羊 毒 鎖 獄 蹴 穏 拒 臣 堅 鬼 釣 呪 挿 脈 械 頷 塞 潮 欄 旨 姓 妹 
#   酸 粧 匹 粋 慮 椅 還 墓 桁 秒 殊 喉 拭 粒 凡 緩 阻 錯 忍 湧 駐 昧 砲 某 愚 扇 敬 維 逸 狩 灰 潔 滑 没 紛 如 鬱 凄 溜 呟 
#   皿 揮 枠 呂 膨 括 唯 忠 耐 預 珍 偽 猿 曖 沿 畳 喧 憎 奮 岳 譲 譜 唱 輩 跳 訂 斉 晋 訊 魂 殴 挟 晶 浪 畑 縦 胆 裸 渉 姫 
#   拉 拝 痴 賛 歓 淡 妨 髭 云 呑 浸 薗 糖 菅 伏 奨 抽 癒 訓 噛 剥 遂 鞄 閥 貿 獲 芝 湿 虹 杉 貧 憂 刀 該 斜 欺 諦 彫 俳 揚 
#   丘 佳 硬 凝 飼 氷 剤 雅 烈 敏 窃 桂 癖 殻 糸 須 棒 鋭 栗 弓 拾 飽 威 軒 辿 貰 垣 頁 軟 粉 馴 陣 貼 往 塔 伴 虚 揃 幽 是 
#   芳 唐 封 掃 昆 戯 詐 婆 斬 炭 戒 稼 冒 泳 裂 溢 繋 尿 零 遇 魁 蘇 泡 鍋 磁 蛇 詮 鈍 煩 墜 撫 泥 虎 孔 宏 煮 盟 彰 誇 徐 
#   陥 嘩 駿 穂 磨 怠 兼 鉱 冠 靖 胃 娠 寧 桑 鎌 偉 眩 呉 兆 拳 沙 隔 酷 慰 掘 朗 琉 叶 朋 帆 架 爪 垂 綺 叔 槽 塀 絹 濁 軸 
#   弥 澤 惜 腐 倫 顎 袖 箇 嫁 懺 嬢 柴 偏 憧 澄 胡 筒 鉢 垢 旗 恒 葛 旦 蓄 漠 把 衡 排 掻 梗 囚 藍 慶 亮 貌 菓 稲 征 涯 乏 
#   蒸 睨 瞼 膜 稚 秩 滞 猛 慨 銘 脂 撲 尊 溶 廷 歪 峰 睡 帝 膚 蚊 媒 枯 彙 壮 眉 矛 擦 聡 椿 励 脅 梶 唄 瑞 雀 詫 壇 煽 焚 
#   赴 沸 需 腫 疾 匿 紺 帽 鼓 潤 宴 貢 痩 恩 謀 旋 盾 寮 刃 啓 誉 肝 吾 菊 紫 蓋 恨 嘆 叱 飴 蘭 暫 剖 綱 頻 殖 擬 符 弧 寸 
#   沼 躊 躇 砕 俯 蛍 苗 幡 剛 郊 亭 堀 宜 噴 桃 芦 踏 肢 戚 陀 鍛 渇 渦 窮 肥 撤 孫 巧 簿 賊 豚 諾 罰 痺 緯 蝶 塩 弊 燥 濯 
#   惚 稽 皺 肺 剰 斐 繊 熟 丹 狼 吊 遭 炊 晒 殆 洒 貫 捉 糞 堤 辱 塊 鳩 醒 滴 曳 硝 枕 僧 循 鎮 盧 奉 諭 醜 伺 傘 滲 餌 咥 
#   燵 巌 鷹 菌 粘 披 塵 槻 貞 胞 戴 筈 勿 堪 鯉 頓 這 淀 笹 羨 卵 梅 舟 培 箸 璧 遥 淳 綴 朴 笠 麦 裾 唾 厄 伎 舐 嘲 套 柵 
#   抄 斎 魯 棟 慈 檎 琴 芽 顕 汲 誓 敢 遷 憩 廻 巾 遮 巣 郭 措 荘 國 悦 穫 憤 蒼 刈 汎 尼 累 妥 盆 騙 軌 賑 贅 韻 悶 堵 鹸 
#   埃 撒 孕 岬 菱 椎 謡 乃 疎 臆 拗 漬 亨 播 妬 訝 艶 勾 霞 溝 捻 陳 銅 虐 攣 肪 犠 牲 摂 蓑 弦 宛 貶 厭 爺 賭 遍 藻 樫 嗅 
#   紐 紳 炬 卸 紋 釧 琢 賠 塁 班 腺 瘍 坪 愉 嘉 乙 湘 股 汁 痙 艦
symbol: " 。 ・ 、 . ✕ *  」 ]  !  :  %  ¥  (  ) / ~  , "
lang_char: |
    w o r d s 領 収 書 車 両 申 込 金 現 内 訳 代 ク レ ジ ッ ト カ ー ド 印 紙 証 券 商 品 任 
    意 自 動 保 険 料 振 入 上 記 の 通 り 正 に 致 し ま た 〒 名 古 屋 市 北 区 山 田 丁 
    目 番 号 株 式 会 社 T E L 表 鉄 A U O 年 月 日 C N 横 シ ス テ ム 経 営 研 究 所 様整 備 検 者 
    費 用 賠 責 重 量 税 指 定 手 続 小 切 種 別 但注 お 客 額 を 訂 も 取 扱 な い 複 写 で は 無 効 
    す 又 後 規 発 行 場 合 充 当 つ き と る 万 円 未 満 非 課 以 下 超時 分 対 象 標 準 率 J B 担 木 
    曽 路 徳 川 店 登 録 明 綱 本昭 和 白 水 飲 食 刺 身 X 個 十 六 ぐ ろ 天 婦 羅 黄 揚 げ べ 比 膳 
    計 点こ 来 誠 あ が う ご さ 消 伝 票 等 a p l t i n セ ル フ 町 愛 知 県 東 大 根 S 売 へ引 Y K I M P 
    軽 油 数  単 価 @ 体 承 認 利 有 期 限 企 業 コ 処 理 付 y 問 せ ア ポ ロ ヨ ン 受 中 み 礦 支タ 払 方 法 
    括 か ん 志 賀 公 園 城 楽 イ 可 能 ボ D 反 映 れ m z ギ ブ ゼ ラ 便 獲 得 予 購 常 G v e メ や 初 層 甲 グ 
    言 ざ 森埋 わ

experiment_name: 'ja_receipt_cpu_demo'
train_data: 'all_data'
valid_data: 'all_data/val'
manualSeed: 1111
workers: 4            # single worker for CPU
batch_size: 16         # reduce load per batch
num_iter: 1000       # fewer iterations for demo
valInterval: 500     # validate more frequently
saved_model: 'saved_models/japanese_g2.pth'       # start from scratch or load Japanese pre‑trained
FT: True
optim: False
lr: 1.0
beta1: 0.9
rho: 0.95
eps: 1e-8
grad_clip: 5
select_data: 'train'
batch_ratio: '1'
total_data_usage_ratio: 1.0
batch_max_length: 34
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
data_filtering_off: False
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: True
freeze_FeatureFxtraction: True
freeze_SequenceModeling: False
